### ISSUE TITLE
Search/Edit AIML empty page

### ISSUE THREAD

**Issue by samuelpereira** [Program-O/Program-O#128]
Hi, 

I always a get empty page when i go to this page, Search/Edit AIML!
I have the lastest version of Program-O.

How can i solve this ?

Thanks

**Comment by Dave-Morton** [comment]
Take a look at the log files (in the logs folder), and please report back anything that you find.

Also, did you download the latest version from the MASTER branch (this is the default action), or from DEV (you have to *actively* select the DEV branch, so you would know if you got it from there)?

**Comment by samuelpereira** [comment]
Hi,

On the logs folder the files are not changed... 

total 16
-rw-r--r-- 1 root root  175 Oct  2  2015 admin.error.log
-rw-r--r-- 1 root root 1080 Oct  2  2015 debug_formvars.txt
-rw-r--r-- 1 root root 4505 May 19 10:12 index.php

On the apache logs, i dont see any error.

I have the master version, i had download a zip.
Now, I have clone again, from the master branch, but the problem is the same...

**Comment by Dave-Morton** [comment]
What are the contents of the file admin.error.log? When checking, it's best to first delete that file, go to the Search/Edit panel of the admin page, then view the log file, so as to only see a single instance of all errors triggered. Please post those contents here, or attach the log to your post.

**Comment by samuelpereira** [comment]
I have deleted the file!
I go to the Search/Edit panel, but the file is not created...

<img width="1423" alt="screen" src="https://cloud.githubusercontent.com/assets/3584195/15400685/49be3538-1de4-11e6-93bb-b2a64ced8f12.png">

**Comment by Dave-Morton** [comment]
Interesting. SO we know that the main script is running, but the contents of search.php are not being displayed.
Ok, which browser are you using, and with what operating system? And can you see any errors in the browser's JavaScript console?

**Comment by Dave-Morton** [comment]
After a bit of investigating, it looks like the JavaScript responsible for displaying the page is not running, probably due to some sort of JavaScript error. I've tested this on my Windows 10 machine using Firefox, Google Chrome, Internet Explorer, the Edge browser, Opera and Safari, and it all works just fine for me, so for now I'm at a loss unless there is something to see in your browser's error console.

**Comment by samuelpereira** [comment]
Hi again,
Sorry for delay...

This is the error on console:

Blocked loading mixed active content "http://yui.yahooapis.com/3.18.0/build/yui/yui-min.js"[Learn More] index.php

I think this is a problem because i'm using a SSL connection on the bot.. and this http its not allowed..

**Comment by samuelpereira** [comment]
I have disabled ssl and the problem is solved!

Thanks for your help :)

**Comment by RamboVital** [comment]
Sounds like the problem I had.  Your using HTTPS like myself as well.  
https://github.com/Program-O/Program-O/issues/113

**Comment by samuelpereira** [comment]
I will look, Thanks

**Comment by Dave-Morton** [comment]
No worries, but rather than disable SSL, it would be better to use the YUI script locally (which is already being implemented in the DEV branch). This was an issue previously, in another issue, but there were different symptoms, so I didn't catch it right away. I still have a bit more testing to do on the DEV branch before I can feel comfortable with making the merge, but with me now being on summer break from school, I'll have more time in the upcoming weeks to complete that testing. Feel free to download the zip file from the DEV branch (it can be found on the main page, in a fancy select box on the upper right of the main content container) and give it a try.

**Comment by Dave-Morton** [comment]
@RamboVital you beat me to the punch! Well done with that. :D
