### ISSUE TITLE
user defined aiml

### ISSUE THREAD

**Issue by OverlanAI** [Program-O/Program-O#366]
Seems at some point after v. 2.6.7 the db will only add user name many times with the rest all nulls in the table USER DEFINED AIML. I use Geekcaves LEARN.aiml in the past and worked well enough before. 
It made use of xsplit and xfind and i forget what other voodoo it did lol.
Anyway I would like to know more about the change to that section of program 0 and what php files would be processing the learn.aiml functions so i can better sort out why it no longer learns like it use to.

TNX, be kind this is my first report to this project :)

**Comment by Dave-Morton** [comment]
Hi, @OverlanAI and thanks for letting us know about this. That AIML file you mention isn't really mine. It was created by Steve Worswick, a good friend of mine and multiple winner of the Loebner Prize, a chatbot competition that sees the best chatbots in the world compete to see which is the "Most Human". :smile:

Please tell me, are you seeing any error log entries that might be relevant to this issue? If so, please post examples of the log entries involved. In the meantime I'll do some testing on my end to see what I can see. thanks.

**Comment by OverlanAI** [comment]
Okay tnx, i will poke around the logs when i get back home. I did find that adding the learn file did not really hurt anything other than i had to empty the table as it was all filled with junk not useful aiml data anymore.
You can import it and do a few chats with your bot then look at the db table. After that i just removed that file with no harm done.
To me i would like to see what learn did as AIML as a core php option so that it can do the same function but be under better control in core and no longer need AIML Voodoo.
Persistaint learning is one of the goals i have in mind and that was as close as i could find that could work. At some point i will explain my project and how i am using your cool program.
Program O was exactly what i needed and i am having good results interfacing it via another platform called OpenSimulator and its powerful scripting lang. LSL. I have worked out how to get the NPCs there to use Progam O as its back end (OverlanAI was born) and give the NPCs there real AI, but that's a long story.

**Comment by Dave-Morton** [comment]
Something that you may be interested in is the "unknown inputs" section of the admin pages. It's a place that shows botmasters user inputs that have triggered the default AIML response, giving you an idea of what users are "saying" that the bot didn't have a response for. While it's not as comprehensive as using `<learn>` tags, it at least gives you an idea of what you need to work on for the bot. This feature isn't as fully developed as I would like right now, I think it's a good start.

**Comment by OverlanAI** [comment]
Yes, I make good use of that and have in fact fed my bots with rss text feeds as its input for testing and correcting. It is quite fun to monitor the chat and debug things at the same time why it learns about life on our crazy ball of dirt.  It was my first clue that learn no longer worked like it use to.
Anyway I will be getting out my code hammers soon and see waz up with dat soon.
tnx again

**Comment by OverlanAI** [comment]
function make_learn($convoArr, $pattern, $template) in parse_aiml.php
The values are not getting passed to the function. It had nothing to do with learn tag or the aiml.
The only value that makes it to the function is convo_id, the others are null.
I am still sorting it out line by line from the last known good version of that file.

tnx

**Comment by OverlanAI** [comment]
Humm ran out of time looking for it in that file. Its rather complex in there.
I swapped out that file with a known good version in the 2.8.9 and it is working ok again.
The table is filled and the AI is using it as expected. All other files but that one are current with 2.8.9 so i know the problem is in there someplace.
tnx

**Comment by OverlanAI** [comment]
Why finding the flaw in 2.8.9 (dev) with learn mode, it occurred to me that it would be useful to add an enable flag so that if I do not what my bot to learn things from sources other than my own I can simply have it ignore <learn> tags.
Learn is a love/hate thing but seems doable as I was poking around your code.

Tnx (sometimes the simple things are the hardest) Have fun.

**Comment by Dave-Morton** [comment]
I've been poking around in both the database and the code, and it turns out that the aiml_userdefined table is, indeed, being written to. the problem was in the admin panel for the table. I've fixed the bug and it works, but I notice that the version of learn.aiml that I have seems to not want to play nicely with Program O, and dumps some strange things into the table. I'm looking into that bit still.

**Comment by OverlanAI** [comment]
[learn.zip](https://github.com/Program-O/Program-O/files/1775922/learn.zip)
That is the current file i use here, i do not recall changing anything from there kind offering of that aiml.
If i did edit it, it would have been html tags or simple a typo.
I am still using parse_aiml.php from a last known good version of that file in 2.8.9.
Anyway it sounds like progress to me and i will test it out soon as i am able.
"dumps some strange things into the table" caught my eye if there is something i can check in my table let me know but just browsing mine i did not notice anything that looked out of place.
Thanks for taking a look at the problem.

**Comment by Dave-Morton** [comment]
When you get the time, try the latest release from the `DEV` branch. that's where I pushed the latest changes last night. Hopefully that will at least let you see the user defined AIML from the admin page.

**Comment by OverlanAI** [comment]
Okay i am testing this from dev and found new problems again that deal with the same file i still have to swap out. ( parse_aiml.php ), because this time it is not dealing <persion?>  so i cant check passed that with out reverting that file. (swapping it fixes both problems still).
As far as the admin edit, The DELETE flag on each file it list is not seen for each one in the list, where as before you last changes it was ok.
Anyway i am still testing and i will try to narrow it down better than this quick drive by update to the problems i am still seeing.
TNX (passes out the code hammers and rum)

**Comment by Dave-Morton** [comment]
@OverlanAI When did you download the version you're testing? I just pushed a new round of bug fixes this morning, so if you grabbed it before that, then you may want to get the latest once more.

**Comment by OverlanAI** [comment]
Okay, yes i had pulled just before you updated today and i am running what is in dev again.
So far it has not added anything to the table yet after i cleared for testing using learn but sometimes it takes it awhile to add something new, so i will let it run over night chatting to my other AI system and see how it goes.
I will be adding in few minor things i see if no one has not already given feed back yet but they are minor fluff things.
tnx

**Comment by OverlanAI** [comment]
Well The good news is that most everything works quite well, all but my main problem that deals with learn and it populating the table.
Now i have to swap out both parse files (aiml and xml) to get learn to fill the table.

BUT i may have jumped the gun about program O in that i never did ask if it was the intent to make program O work in the manor i stumbled on using learn.aiml  (learn tags) in the first place.
If it was never the intention and just me assuming that it was then i can use my own hacks and not bother every one else about it.
tnx

**Comment by Dave-Morton** [comment]
Well, the intention is pretty straightforward here. When you use the `<learn>` tag, Program O takes the new category being created and places it into the aiml_userdefined table for the bot and user it was created for. then Program O *should* look in that table on subsequent volleys to see if it can match user input to any categories stored there _BEFORE_ it looks in the main aiml table. If it matches one, then that category is parsed and output, but if nothing relevant is found it searches the main aiml table for something to parse.

The current state of this feature may still be broken, so if you want to investigate further, I would appreciate any information that you want to send our way.. I'd really like to get this feature fully operational, and if you're willing to help in this area, I would humbly and gratefully accept the assist. :smile:

**Comment by OverlanAI** [comment]
Over my 30 years of coding and here real dev coders tell me CANT, i decided to prove them wrong.
AI is not new but humans fear learning AI.
I asked show me you fail, send me 100 ways you tryed and it did not work, and they had nothing.
I want learn as stored and used no matter what ppl fear so that there is a real thing to hate.
But i will never take 100 resions whay i cant do something with out it existing to start with.
so lets do this!
tnx

**Comment by OverlanAI** [comment]
Okay then ill say , that currently 'learn' is still not persisting to the table using the best aiml versions of that idea i can find. 
I hack and make stuff work but it is just so we can get on with the bigger 1km hacker view.
so its all good to one point of view is persiatant learning of AI is not ment.
If i know the intentions better then i know what we will do next.

**Comment by Dave-Morton** [comment]
@OverlanAI I'm the same way. don't ever tell me I can't do something. I'll end up proving you wrong. We should probably find a way to chat directly with each other, rather than leaving messages in a GitHub issue. I have several apps and programs that I use to communicate directly, such as Skype, Google Hangouts (now Google Meet) or Facebook messenger. I have other means as well, but those three are my "go to's". If that fails to interest you, there's also email. :smile:

**Comment by OverlanAI** [comment]
cool, my use is progamO is a back end to user made worlds (opensim) to make humans that interact there say "what did that just say?" and why is it mad at me trying to get me, or why is it happy and dances with me. 
My worlds we make lack real AI, so we intend to break that and make it the norm.
it must learn no matter what we think to be intresting and it must also make a user say"wait what did that just say" and spend time.
anyway My use has nothing to do with it as a web page and every thing to do with "What did you just call me?" lol
In learn mode it not only knows who that was but also knows them the last time they interact.
My AI as programO really will get mad in vr or be nice as it learns about that user.
Anyway ill poke a few ppl i know and have them take a look and there as wild as me but damm you got the good stuff :-)

**Comment by OverlanAI** [comment]
I sent out a few pokes to ppl i like at MIT and berk, there all ass hats but dammed good and love me poke when i see something cool like your project, 
Sometimes they do pull there head out there butt and help.
tnx (hackers go fast, the rest just think all day)

**Comment by OverlanAI** [comment]
Now learn mode to me is a love hate thing, when it works your AI will start saying things worng for a few days but after about 3 days it starts to not be so odd if you leave it alone.
After about one week of that it sorts it out and i find "damm i love my AI" now and i never needed to correct it. but to do that i had to let it out of the box.
Its box is in VR so all the silly fear humans have is one switch click,
That got in there heads now and most come back,
Anyway your dog and my cat remain in the same ideas because they are both critters.
My idea is to take all this cool work and have it slap the user in to "Better look at me".
It has to learn and store it, simple as that

**Comment by OverlanAI** [comment]
anyway i sent out the call to the ass hats that love a good hacker and to know that someone said cant be done. 
I got a good crew and there not about money because POC (Proof Of Consept) matters most.
we do it just just cuz i guess lol
Any way i got tow of them to take a look at you porject now and hippo to make sure its solid.

**Comment by OverlanAI** [comment]
God help us lol

**Comment by OverlanAI** [comment]
BTW hacker is not bad, it just means focused and wants to learn, The term hacker is not something to fear and just means we like to know how it works. Not ment in a bad way like ppl think the word is.
FidoOP226 .. fidonet was before there was this and hackers made what you all use as internet now
so dont get my word as HACKER mixed up with bad ppl.
I got the scars, i know to say that and its all good stuff here.

**Comment by OverlanAI** [comment]
So lets get on with this lol
tnx

**Comment by OverlanAI** [comment]
I am working on a cleaned up version of learn.aiml for testing with. Mostly the one i attached had small errors with excessive spacing that sometimes cause xsplit parse to puke on long input lines.
Function wise it remains the same and still working fine with my file rollbacks.
At some point it might be helpful so we have something to go by once you have more of it working again.
Once my current aiml has hit around 5k new learned and stored data i will make the clean version of that aiml. available here.
It took me awhile to find why it was having issues with long input lines so i want to be sure first but so far no more XpukeSplit problems after i got rid of the excessive spaces.
There are a few gotchas to adding in learn.aiml to an existing set where we might have a * is a * in the way (there are others too) of the same one learn uses but i will add a note about that to the zip and is quite easy to check and change in the editor if there is a dupe like that.
TNX

**Comment by OverlanAI** [comment]
We decided to hold off on posting Superlearn.aiml since you have already corrected the aiml on geekcave.
What you have there is good enough to test with.
BTW, seems down loading some of the things there no longer works as some kind of DB error.
Anyway we think the best way to deal with bottomless pits that learn becomes is to use BLOB with stored procedures. We know that PDO helps but just to a point. Once the DB hits over say 10 gigs in just what it
 has, makes PDO useless.
All agree for small DB it is easy and faster but not when AI stores everything.
In the simulator world that is the case for every asset and took a lot "How the hell do we do that" kind of thinking.
Its not about where we are, its about what will it be and what then.
Meaning time i adding a few things to get a superlearn mode report using the scoring values you have set. 
Anyway what you have on geekcave (check your site)  is good enough for testing of my posted problem.
tnx

**Comment by Dave-Morton** [comment]
I know that the site has issues. I just haven't had the time to fix it. I'll get to it at some point, just not sure when.

**Comment by OverlanAI** [comment]
We continue with Learn mode and are starting to see the wall now.
Do we let the AI out of it box or not?
Thats the real fear and dream.
In our opinion the best program you can have is the one that scares the crap out of ppl to make them look. Then calm there fear that it is nothing like that.
I still think all that is needed to learn mode is a simple , YES or NO form the botmaster.
Yes means it becomes whatever it can be, No means you have to moderate it all.
Learn can be in 2 modes if you say Yes.
Learn works but is only in memory not stored OR TB of stores every thing.
No matter the moral (what might be some day) is just silly.
AI is in a box anyway CLICK!
Mean time Yah lets do learn the right way as it was meant, Then there is more than just theory of "what is someday" when there not something to point to.After fixing a few things with learn mode, I can say .. Yah it can be creepy! (but hell yah)

TNX (coders code hackers give boot to the head) lol

**Comment by OverlanAI** [comment]
Closing this as not fixed but i will re-open a new report so it will be less confusing after some of the other problems are solved and also get a better consensus about what persistent LEARN should be.
tnx
